---
title: "GSEA after DESeq2"
date: '2022-07-16'
author: 
- name: Sara Formichetti
  affiliation: EMBL Rome
  email: sara.formichetti@embl.it
output:
  prettydoc::html_pretty:
    toc: true
    toc_depth: 3
    number_sections: true
    fig_width: 20
    fig_height: 15
    fig_caption: yes
---

The Rdata containing GSEA results from this Rmd are used in OGlcNAc_early_embryo_Formichetti2023/Btgh_injected_blastocysts_SMARTSeq/src/Rmd/GSEA_morulae_blasto_comparison.Rmd to make the combined GSEA plot including morulae and blastocysts shown in paper figure. 

```{r, eval=FALSE, include=FALSE}

library(prettydoc)

```

```{r Setting general options, include=FALSE}

#knitr::opts_knit$set(width = 150, self.contained = TRUE)

knitr::opts_chunk$set(autodep = TRUE, cache = TRUE, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.width=12, fig.height=8)

```

```{r loading needed packages}

library("DESeq2")
library(ggplot2)
library("ggrepel")
library("vsn")
library(data.table)
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)
library(GOSemSim)

```

```{r loading necessary Rdata}

load("Rdata/res_all.Rdata")
load("Rdata/gene_map_dt.Rdata")

```

# Gene Set Enrichment Test

```{r preparing go data for similarity analysis}

mmBP <- godata('org.Mm.eg.db', ont="BP")
mmMF <- godata('org.Mm.eg.db', ont="MF")
mmCC <- godata('org.Mm.eg.db', ont="CC")

```

```{r GSEA}

# choosing similarity cutoff for simplification of gsea results
sim_cutoff <- 0.6

### Function which simplifies a gse result by semantic similarity, in the same way it is done by the clusterProfiler::simplify function (which however only takes gseGO results) 
simplify_gse <- function (my_gse_res, my_semdata, my_sim_cutoff = sim_cutoff) {
  my_gse_sim <- mgoSim(my_gse_res$ID, my_gse_res$ID, semData=my_semdata, measure="Wang", combine=NULL)
  my_gse_sim.df <- as.data.frame(my_gse_sim)
  my_gse_sim.df$go1 <- row.names(my_gse_sim.df)
  my_gse_sim.df <- reshape2::melt(my_gse_sim.df, id.vars = "go1", variable.name = "go2", value.name = "similarity")
  my_gse_sim.df <- my_gse_sim.df[!is.na(my_gse_sim.df$similarity),]
  # adding padj of go1
  my_gse_sim.df <- merge(my_gse_sim.df, my_gse_res[, c("ID", "p.adjust")], by.x="go1", by.y="ID")
  # adding padj pf go2
  my_gse_sim.df$go2 <- as.character(my_gse_sim.df$go2)
  my_gse_sim.df <- merge(my_gse_sim.df, my_gse_res[, c("ID", "p.adjust")], by.x="go2", by.y="ID", suffixes = c(".go1", ".go2"))
  # df with IDs which have similarity > cutoff
  to_remove <- my_gse_sim.df[my_gse_sim.df$similarity > sim_cutoff & my_gse_sim.df$similarity != 1, ]
  # for each pair of IDs, choosing the one with lowest padj  
  go1_to_remove <- to_remove[to_remove$p.adjust.go1 >= to_remove$p.adjust.go2, "go1"]
  go2_to_remove <- to_remove[to_remove$p.adjust.go2 > to_remove$p.adjust.go1, "go2"]
  my_gse_res_f <- my_gse_res[!(my_gse_res$ID %in% unique(c(go1_to_remove, go2_to_remove))), ]
  return(my_gse_res_f)
}

### Function which: creates a vector of -log10(pval)*sign(log2FC) for the DESeq result of a specific comparison, sorted in decreasing order and named with gene ids; uses this vector for Gene Set Enrichment Analysis using package clusterProfiler; simplify the result by semantic similarity
perform_all_gsea <- function (my_res) {
  my_rank_stat <- -log10(my_res[my_res$baseMean > 10, ]$pvalue)*sign(my_res[my_res$baseMean > 10, ]$log2FoldChange)
  my_gene_list <- setNames(object = my_rank_stat, nm = rownames(my_res[my_res$baseMean > 10, ]))
  # gene list for GSEA needs to be sorted in decreasing order
  my_gene_list <- my_gene_list[order(my_gene_list, decreasing = TRUE)]
  my_gene_list <- na.omit(my_gene_list)
  BP <- gseGO(geneList=my_gene_list, 
             ont ="BP", 
             keyType = "ENSEMBL", 
             minGSSize = 10, 
             maxGSSize = 500, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Mm.eg.db, 
             pAdjustMethod = "BH")
  BP <- setReadable(BP, OrgDb=org.Mm.eg.db, keyType = "ENSEMBL")
  BP@result <- simplify_gse(BP, my_semdata = mmBP)
  MF <- gseGO(geneList=my_gene_list, 
             ont ="MF", 
             keyType = "ENSEMBL", 
             minGSSize = 10, 
             maxGSSize = 500, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Mm.eg.db, 
             pAdjustMethod = "BH")
  MF <- setReadable(MF, OrgDb=org.Mm.eg.db, keyType = "ENSEMBL")
  MF@result <- simplify_gse(MF, my_semdata = mmMF)
  CC <- gseGO(geneList=my_gene_list, 
             ont ="CC", 
             keyType = "ENSEMBL", 
             minGSSize = 10, 
             maxGSSize = 500, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Mm.eg.db, 
             pAdjustMethod = "BH")
  CC <- setReadable(CC, OrgDb=org.Mm.eg.db, keyType = "ENSEMBL")
  CC@result <- simplify_gse(CC, my_semdata = mmCC)
  return(list(BP, MF, CC))
}

all_gsea_activeVsDead <- perform_all_gsea(res_all$active_vs_dead)
all_gsea_activeVsCtrl <- perform_all_gsea(res_all$active_vs_ctrl)
all_gsea_deadVsCtrl <- perform_all_gsea(res_all$dead_vs_ctrl)

```

```{r table of GSEA, results='asis'}

knitr::kable(as.data.frame(all_gsea_activeVsDead[[1]]), caption = "active vs dead - Biological Process GO")
knitr::kable(as.data.frame(all_gsea_activeVsDead[[2]]), caption = "active vs dead - Molecular Function GO")
knitr::kable(as.data.frame(all_gsea_activeVsDead[[3]]), caption = "active vs dead - Cellular Component GO")
knitr::kable(as.data.frame(all_gsea_activeVsCtrl[[1]]), caption = "active vs ctrl - Biological Process GO")
knitr::kable(as.data.frame(all_gsea_activeVsCtrl[[2]]), caption = "active vs ctrl - Molecular Function GO")
knitr::kable(as.data.frame(all_gsea_activeVsCtrl[[3]]), caption = "active vs ctrl - Cellular Component GO")
knitr::kable(as.data.frame(all_gsea_deadVsCtrl[[1]]), caption = "dead vs ctrl - Biological Process GO")
knitr::kable(as.data.frame(all_gsea_deadVsCtrl[[2]]), caption = "dead vs ctrl - Molecular Function GO")
knitr::kable(as.data.frame(all_gsea_deadVsCtrl[[3]]), caption = "dead vs ctrl - Cellular Component GO")

```

```{r GSEA plots, include = TRUE}

dotplot(all_gsea_activeVsDead[[1]], showCategory=10, split=".sign", title = "active vs dead - BP GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_activeVsDead[[2]], showCategory=10, split=".sign", title = "active vs dead - MF GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_activeVsDead[[3]], showCategory=10, split=".sign", title = "active vs dead - CC GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_activeVsCtrl[[1]], showCategory=10, split=".sign", title = "active vs ctrl - BP GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_activeVsCtrl[[2]], showCategory=10, split=".sign", title = "active vs ctrl - MF GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_activeVsCtrl[[3]], showCategory=10, split=".sign", title = "active vs ctrl - CC GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_deadVsCtrl[[1]], showCategory=10, split=".sign", title = "dead vs ctrl - BP GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_deadVsCtrl[[2]], showCategory=10, split=".sign", title = "dead vs ctrl - MF GO", font.size = 10) + facet_grid(.~.sign)
dotplot(all_gsea_deadVsCtrl[[3]], showCategory=10, split=".sign", title = "dead vs ctrl - CC GO", font.size = 10) + facet_grid(.~.sign)

```

```{r saving Rdata}

save(all_gsea_activeVsDead, file = "Rdata/all_gsea_activeVsDead.Rdata")
save(all_gsea_activeVsCtrl, file = "Rdata/all_gsea_activeVsCtrl.Rdata")
save(all_gsea_deadVsCtrl, file = "Rdata/all_gsea_deadVsCtrl.Rdata")

```

```{r sessioninfo, echo = TRUE, results = 'markup'}

sessionInfo()

```